### PR TITLE
Modifications in queries and command line calls

### PR DESCRIPTION
**Pull request by 3sigma**
1. query() can be called directly (added call to session() inside.
update() has been modified consequently
2. added query_str() to call function who return strings (like help or
traffic)
3. added hostname and port as mandatory arguments for the command line
(a computer maybe connected to more than one router and Dovado could not
be the first one in the list)
4. added "command" as first argument for the command line
5. README modified consequently

### CODE REVIEW

**Comment by molobrakos** [comment]
Thanks a lot for contributing!
2): Out of curiosity hat model(s) support the `traffic` command and what does the response look like? (I own a 4GR and a PRO and I can't find the command in the manual (i.e. http://www.dovado.com/images/Firmware/PRO_Reference_manual83X.pdf)

3, 4) Good suggestions. The code in `__main__` was initially a quick and dirty sample just to test basic functionality, and the main usage of this lib would be as an API. I'll add something like what you suggest.

**Comment by 3sigma** [comment]
Hello,

I have a Tiny. With my modifications, the response for "update" is:

{
   "api version": "1.5",
   "connected devices": "MODEM",
   "connection": "usb1",
   "date": "2017-02-15",
   "external ip": "100.68.213.86",
   "firmware revision": "7.3.17",
   "modem status": "CONNECTED",
   "new firmware available": "no",
   "product name": "Dovado TINY",
   "signal strength": "25 % -98 dBm (3G)",
   "sms": "enabled",
   "sms total": "4",
   "sms unread": "0",
   "time": "09:26",
   "traffic modem rx": "2479",
   "traffic modem tx": "3738"
}

and the response for "traffic" is:

208150113348939 2479 / 3738

The first number is the SIM IMSI.


The response for "help" is:

Dovado API

Commands:
                 help (show this help)
                 exit|quit|bye (close the telnet session)
                 user [username] (log in as user)
                 pass [secret_password] (log in with secret_password)
                 info (prints general information about the router)
                 services (lists services)
                 upgrade (upgrades router to latest available firmware)
                 traffic (displays data usage statistics)

         SMS:
                 sms list (returns number of unread/read messages)
                 sms send [PDU]
                 sms sendtxt NUMBER [ENCODING]
                         NUMBER:international format without the leading 
+. A leading s indicates short SMS (eg s4612345678)
                         ENCODING:ISO|UCS (ISO for ascii < 256). Leave 
blank for autodetection
                 sms recv [ID] (returns PDU with ID or all PDUs in the 
inbox if ID is empty [ID:PDU])
                 sms recvtxt [ID] (returns cleartext SMS with ID or all 
cleartext SMS in the inbox if ID is empty)
                 sms del ID

         Internet:
                 internet [on]/[off]


You have done a great work, it is very useful !

Best regards,

Nicolas

**Comment by molobrakos** [comment]
Apologies for not using your suggestions as is. I made some similar changes while cleaning up the code in general and I think your use cases in the PR are covered now (all commands supported from command line, passing in hostname and port, etc). Please test and report any issues.

**Comment by 3sigma** [comment]
No problem, it was just suggestions ;-)

I will test soon.

Best regards,

Nicolas

**Comment by molobrakos** [comment]
Closing this, please let me know if you are still missing any functionality.

**Pull request closed without merging**
